vton/main/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test

from django.conf.urls import url

app_name = 'main'
urlpatterns = [
	url(r'^$',views.index,name="index"),
	url(r'^goplist/$', views.goplist,name="goplist"),
	url(r'^ajax/GOP/$', views.fGOP,name="fGOP"),	
	url(r'^ajax/GOPFull/$', views.fGOPFull,name="fGOPFull"),	
]

vton/vton/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
]

vton/main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from datetime import datetime

# Create your models here.

class Garment(models.Model):
	name = models.CharField(max_length=20,default='EMPTY')
	cloth_path = models.CharField(max_length=5000,default='EMPTY')
	cloth_mask_path = models.CharField(max_length=5000,default='EMPTY')

	# raw_s3_link = models.CharField(max_length=5000,default='EMPTY')

	def __str__(self):
		return str(self.pk) + " - " + str(self.name)


class Pose(models.Model):
	name = models.CharField(max_length=20,default='EMPTY')
	image_path = models.CharField(max_length=5000,default='EMPTY')
	image_parse_path = models.CharField(max_length=5000,default='EMPTY')
	pose_path = models.CharField(max_length=5000,default='EMPTY')

	def __str__(self):
		return str(self.pk) + " - " + str(self.name)


class GOP(models.Model):
	garment = models.ForeignKey(Garment,on_delete=models.CASCADE)
	pose = models.ForeignKey(Pose,on_delete=models.CASCADE)
	warp_cloth_path = models.CharField(max_length=5000,default='EMPTY')
	warp_cloth_mask_path = models.CharField(max_length=5000,default='EMPTY')
	tryon_path = models.CharField(max_length=5000,default='EMPTY')
	start_time = models.DateTimeField(default=datetime.now)
	end_time= models.DateTimeField(default=datetime.now)
	def __str__(self):
		return str(self.pk) + " - " + str(self.garment.name) + " - " + str(self.pose.name)


class Setting(models.Model):
	is_running = models.BooleanField(default=False)
	pose = models.CharField(max_length=5000,default='EMPTY')
	garment = models.CharField(max_length=5000,default='EMPTY')
	def __str__(self):
		return str(self.pk) + " - " + str(self.garment) + " - " + str(self.pose)

vton/main/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import time
from django.shortcuts import render
from django.conf import settings
from django.http import HttpResponse,JsonResponse
from django.shortcuts import render,redirect,get_object_or_404
from django.template.context_processors import csrf
from pprint import pprint
import os,sys
import shutil
from main.models import Garment,Pose,GOP,Setting
from django.core.paginator import Paginator
import random
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime

# 002875 Garment id , bad example of masking

#coding=utf-8
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image
import argparse
from main.cp_dataset import CPDataset, CPDataLoader
from main.networks import GMM, UnetGenerator, load_checkpoint
from main.utils_inference import main,gsp,gfp
# Create your views here.

# Create your views here.
def index(request):
	cur_setting=None
	for cur_setting in Setting.objects.all():
		pass

	if not cur_setting:
		cur_setting = Setting()
		cur_setting.save()



	choice_count = 1

	if 'p' in request.GET.keys():
		pose_name = request.GET.get('p')
		poses = Pose.objects.filter(name=pose_name)
		if poses.count() != 1: 
			poses = Pose.objects.all().order_by('?')[:choice_count]
	else:
		poses = Pose.objects.all().order_by('?')[:choice_count]

	garments = Garment.objects.all().order_by('?')[:choice_count]
	C = {
		'pose' : poses[0],
		'garment' : garments[0],
		'is_running' : cur_setting.is_running,
	}
	C.update(csrf(request))
	return render(request,'index.html',C)


def goplist(request):
	C = {
		'gops' : GOP.objects.all()[::-1][:50]
	}
	C.update(csrf(request))
	return render(request,'gop_list.html',C)

@csrf_exempt
def fGOPFull(request):
	start_time = datetime.now()
	t1 = time.time()
	from binascii import a2b_base64
	cur_setting=None
	for cur_setting in Setting.objects.all():
		pass

	if not cur_setting:
		cur_setting = Setting()
		cur_setting.save()

	# cur_setting.is_running = False
	# cur_setting.save()

	print(cur_setting.is_running)
	if cur_setting.is_running:
		return JsonResponse({
			'message' : 'come back later, running ' + str(cur_setting),
		})

	cur_setting.is_running = True
	cur_setting.save()

	garment_name = request.POST.get('garment_name')
	pose_image_data = request.POST.get('pose_image_data')

	tmp_dir = settings.BASE_DIR + '/static/tmp/'
	if os.path.exists(tmp_dir):
		shutil.rmtree(tmp_dir)
	os.makedirs(tmp_dir)

	input_pose_path = tmp_dir + "/input_pose.jpg"
	if os.path.exists(input_pose_path):
		os.remove(input_pose_path)
	binary_data = a2b_base64(pose_image_data)
	fd = open(input_pose_path, 'wb')
	fd.write(binary_data)
	fd.close()

	#resize image
	from main.utils_inference import resize_image
	resize_image(input_pose_path)


	JPPNET_DIR = settings.BASE_DIR + "/../LIP/"
	py_file = JPPNET_DIR + 'evaluate_parsing_JPPNet-s2.py'
	jpp_input_path = JPPNET_DIR + 'datasets/examples/images/input_pose.jpg'
	jpp_output_path_parsing = JPPNET_DIR + 'output/parsing/val1/input_pose_vis.png'
	if os.path.exists(jpp_input_path):
		os.remove(jpp_input_path)
	shutil.copy(input_pose_path,jpp_input_path)

	import subprocess
	p = subprocess.Popen(["python",py_file], cwd=JPPNET_DIR)
	p.wait()

	#create keypoints json
	py_file = JPPNET_DIR + 'evaluate_pose_JPPNet-s2.py'
	jpp_output_path_pose = JPPNET_DIR + 'output/pose/val1/input_pose.txt'
	p = subprocess.Popen(["python",py_file], cwd=JPPNET_DIR)
	p.wait()

	parse_path = tmp_dir + "/pose_parse.png"
	keypoints_txt_path = tmp_dir + "/pose_keypoints.txt"
	keypoints_json_path = tmp_dir + "/pose_keypoints.json"
	shutil.copy(jpp_output_path_parsing,parse_path)
	shutil.copy(jpp_output_path_pose,keypoints_txt_path)

	f = open(keypoints_txt_path,'r')
	keypoints_str = f.read()
	f.close()

	import json
	sample_kp_path = settings.BASE_DIR + '/static/sample_kp.json'
	with open(sample_kp_path, "r") as read_file:
		sample_kp = json.load(read_file)
	
	sample_kp['people'][0]['pose_keypoints'] = []

	keypoints_list = keypoints_str.split(" ")
	point_dict = {}
	for i in range(16):
		px = int(keypoints_list[2*i])
		py = int(keypoints_list[2*i+1])
		point_dict[i] = (px,py)

		if i <=13:
			sample_kp['people'][0]['pose_keypoints'].append(px)
			sample_kp['people'][0]['pose_keypoints'].append(py)			
			sample_kp['people'][0]['pose_keypoints'].append(0)			

	for i in range(3):
		sample_kp['people'][0]['pose_keypoints'].append(point_dict[0][0])	
		sample_kp['people'][0]['pose_keypoints'].append(point_dict[0][1])
		sample_kp['people'][0]['pose_keypoints'].append(0)			

	sample_kp['people'][0]['pose_keypoints'].append(point_dict[15][0])
	sample_kp['people'][0]['pose_keypoints'].append(point_dict[15][1])
	sample_kp['people'][0]['pose_keypoints'].append(0)			

	index_json_string = json.dumps(sample_kp,indent=4)
	f = open(keypoints_json_path,'w')
	f.write(index_json_string)
	f.close()

		
	#register a pose id 
	static_dir = settings.BASE_DIR + "/static/"
	cur_pose = Pose()
	cur_pose.save()
	mode = 'train'

	cur_pose.name = "U"+str(cur_pose.pk)
	cur_pose.save()
	pk_image = cur_pose.name
	image_path = gfp(static_dir,'data',mode,'image',pk_image)
	image_parse_path = gfp(static_dir,'data',mode,'image-parse',pk_image)
	pose_path = gfp(static_dir,'data',mode,'pose',pk_image)

	
	shutil.copy(input_pose_path,image_path)
	shutil.copy(parse_path,image_parse_path)
	shutil.copy(keypoints_json_path,pose_path)

	Image.open(image_parse_path).convert('L').save(image_parse_path)

	cur_pose.image_path = gsp(image_path)
	cur_pose.image_parse_path = gsp(image_parse_path)
	cur_pose.pose_path = gsp(pose_path)
	cur_pose.save()

	#call main
	ans = main(garment_name,cur_pose.name)
	garment = Garment.objects.get(name=garment_name)
	pose = cur_pose
	gop = GOP(garment=garment,pose=pose)
	gop.save()

	gop_path = settings.BASE_DIR + '/static/gop/' + str(gop.pk) + "/"
	if not os.path.exists(gop_path):
		os.makedirs(gop_path)

	shutil.copy(ans['warp_cloth_path'],gop_path + "warp_cloth.jpg")
	shutil.copy(ans['output_path'],gop_path + "output.jpg")
	# shutil.rmtree(ans['dir'])

	# print(gop)
	# print(ans['warp_cloth_path'],gop_path+"warp_cloth.jpg")
	# print(ans['output_path'],gop_path + "output.jpg")


	end_time = datetime.now()
	gop.warp_cloth_path = gsp(gop_path + "warp_cloth.jpg")
	gop.tryon_path = gsp(gop_path + "output.jpg")
	gop.start_time = start_time
	gop.end_time = end_time
	gop.save()

	cur_setting.is_running = False
	cur_setting.save()

	t2=time.time()

	return JsonResponse({
		# 'message' : keypoints_str + " | time taken = " + str(t2-t1),
		'message' : 'success',
		'parse_path' : gsp(parse_path),
		'output_path' : gop.tryon_path,
		'warp_path' : gop.warp_cloth_path,
	})

	

def fGOP(request):
	start_time = datetime.now()
	cur_setting=None
	for cur_setting in Setting.objects.all():
		pass

	if not cur_setting:
		cur_setting = Setting()
		cur_setting.save()

	print(cur_setting.is_running)
	if 0:#cur_setting.is_running:
		return JsonResponse({
			'message' : 'come back later, running ' + str(cur_setting),
		})

	cur_setting.is_running = True
	cur_setting.save()
	
	
	garment_name = request.GET.get('garment_name')
	pose_name = request.GET.get('pose_name')

	cur_setting.pose = pose_name
	cur_setting.garment = garment_name
	cur_setting.save()

	print(garment_name,pose_name)
	ans = main(garment_name,pose_name)

	garment = Garment.objects.get(name=garment_name)
	pose = Pose.objects.get(name=pose_name)
	gop = GOP(garment=garment,pose=pose)
	gop.save()
	print(gop)

	gop_path = settings.BASE_DIR + '/static/gop/' + str(gop.pk) + "/"
	if not os.path.exists(gop_path):
		os.makedirs(gop_path)
		print(gop_path)

	pprint(ans)
	shutil.copy(ans['warp_cloth_path'],gop_path + "warp_cloth.jpg")
	shutil.copy(ans['output_path'],gop_path + "output.jpg")
	# shutil.rmtree(ans['dir'])

	print(gop)
	print(ans['warp_cloth_path'],gop_path+"warp_cloth.jpg")
	print(ans['output_path'],gop_path + "output.jpg")

	end_time = datetime.now()
	gop.warp_cloth_path = gsp(gop_path + "warp_cloth.jpg")
	gop.tryon_path = gsp(gop_path + "output.jpg")
	gop.start_time = start_time
	gop.end_time = end_time
	gop.save()

	cur_setting.is_running = False
	cur_setting.save()
	return JsonResponse({
		'message' : 'success',
		'output_path' : gop.tryon_path,
		'warp_path' : gop.warp_cloth_path,
	})

vton/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1" charset="UTF-8"> -->
    <meta charset="UTF-8">
    <title>{% block title%} TRI#D DL : CP-VTON {% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="//cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css">

    {% block styles %}
    {% endblock %}

    <script>
        {% block jquery %}
        {% endblock %}
    </script>
    
</head>
<body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">

                <!-- Header -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'main:index' %}">TRI3D</a>
                </div>

                <!-- Items -->
                <div class="collapse navbar-collapse" id="topNavBar">
                    <ul class="nav navbar-nav navbar-right">   
                        <li>
                            <a href="{% url 'main:index' %}">
                                Try New
                            </a>
                        </li>
                         <li>
                            <a href="{% url 'main:goplist' %}">
                                Last 5 History
                            </a>
                        </li>


                    </ul>
                </div>

            </div>
        </nav>

    
    
    {% block body %}
    {% endblock %}
</body>

{% block scripts %}

{% endblock %}

</html>

vton/main/templates/gop_list.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
{% for gop in gops %}
<div>
	garment_id = {{gop.garment.name}} , pose_id = {{gop.pose.name}} , start_time = {{gop.start_time}} , end_time = {{gop.end_time}}
</div>
<br>
<div>
	<img src="../{{gop.garment.cloth_path}}">
	<img src="../{{gop.pose.image_path}}">
	<img src="../{{gop.warp_cloth_path}}">
	<img src="../{{gop.tryon_path}}">
</div>
<br>
{% endfor %}
{% endblock%}

vton/main/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="container">
	<div class="row">
		To see how garment will look on the person, click Generate GOP button
	</div>
	<div class="row">
		<div style="text-align: center">

			<a id="GOP" style="display:inline" onclick="generateGOP('{{garment.name}}','{{pose.name}}')" class="btn btn-success"> GENERATE GOP </a>
			<a id="GOPFull" style="display:none" onclick="generateGOPFull('{{garment.name}}')" class="btn btn-success"> GENERATE FULL GOP </a>
			<a onclick="location.reload()" class="btn btn-warning"> Refresh Combination </a>
		  	<input style="display:inline" id="pose_image_id" type="file" name="pose_image_name" onchange="readURL(this);">
			
			
		</div>		
	</div>
	<div class="row">
		<div class="col-sm-3" style="background-color:white;">
		    <div style="text-align: center">
		        <h3>Gar {{garment.name}}</h3>
		    </div>
		    <div style="text-align: center">
			    <div class="panel panel-default">
			        <div class="panel-body">
						<img id="input_garment" src="{{garment.cloth_path}}">            
			        </div>
			    </div>
		    </div>

		    <div style="text-align: center">
			    <div class="panel panel-default">
			        <div class="panel-body">
						<img src="{{garment.cloth_mask_path}}">            
			        </div>
			    </div>
		    </div>
		</div>	

		<div class="col-sm-3" style="background-color:white;">
		    <div style="text-align: center">
		        <h3>Pose {{pose.name}}</h3>
		    </div>
		    <div style="text-align: center">
			    <div class="panel panel-default">
			        <div class="panel-body">
						<img id="input_pose" src="{{pose.image_path}}">            
			        </div>
			    </div>
			</div>

			<div style="text-align: center">
			    <div class="panel panel-default">
			        <div class="panel-body">
						<img id="input_pose_parse" src="{{pose.image_parse_path}}">            
			        </div>
			    </div>
			</div>
		</div>	

		<div class="col-sm-6" style="background-color:white;">
		    <div style="text-align: center">
		        <h3 id="output_h3">Output</h3>
		    </div>
		    <div style="text-align: center">
			    <div class="panel panel-default">
			        <div class="panel-body">
			        	<img id="warp_img" src="">            
						<img id="output_img" src="">      
			        </div>
			    </div>
			</div>
		</div>	
	</div>	
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">

	function readURL(input) {
        images_ul = document.getElementById('images_ul');
        
        var reader = new FileReader();
        reader.index = 0;
        reader.onloadend = function (inp) {                             
            document.getElementById('input_pose').src=inp.target.result;
            document.getElementById('input_pose_parse').src='';
        };
        reader.readAsDataURL(input.files[0]);
        
        document.getElementById("pose_image_id").disabled = true;
        document.getElementById("GOP").style.display = 'none';
        document.getElementById("GOPFull").style.display = 'inline';
    }

	function getCookie(c_name) {
	    if(document.cookie.length > 0) {
	        c_start = document.cookie.indexOf(c_name + "=");
	        if(c_start != -1) {
	            c_start = c_start + c_name.length + 1;
	            c_end = document.cookie.indexOf(";", c_start);
	            if(c_end == -1) c_end = document.cookie.length;
	            return unescape(document.cookie.substring(c_start,c_end));
	        }
	    }
	    return "";
	}

	function getBase64Image(img) {
	  var canvas = document.createElement("canvas");
	  canvas.width = img.width;
	  canvas.height = img.height;
	  var ctx = canvas.getContext("2d");
	  ctx.drawImage(img, 0, 0);
	  var dataURL = canvas.toDataURL("image/png");
	  return dataURL.replace(/^data:image\/(png|jpg);base64,/, "");
	}

	function generateGOPFull(gname){
		document.getElementById("output_h3").innerHTML = 'GENERATING GOP FULL .... '
		$.ajax({
              url:'/ajax/GOPFull/',
              method:'POST',
              data : { 
              	'garment_name' : gname,
              	'pose_image_data' : getBase64Image(document.getElementById("input_pose"))
              },
              success: function(data) {

           		if(data['message'] == 'success'){
           			document.getElementById('warp_img').src = data['warp_path'];    
           			document.getElementById('output_img').src = data['output_path'];    
           			
           		}
           		else{
           			alert(data['message']);
           		}
           		document.getElementById('input_pose_parse').src = data['parse_path']
           		document.getElementById("output_h3").innerHTML = 'Output'	
           		
              },
         });

	}

	function generateGOP(gname,pname){
		document.getElementById("output_h3").innerHTML = 'GENERATING GOP .... '
        $.ajax({
              url:'/ajax/GOP/',
              data : { 
              	'garment_name' : gname,
              	'pose_name' : pname,
              },
              success: function(data) {

           		if(data['message'] == 'success'){
           			document.getElementById('warp_img').src = data['warp_path'];    
           			document.getElementById('output_img').src = data['output_path'];    
           			
           		}
           		else{
           			alert(data['message']);
           		}
           		document.getElementById("output_h3").innerHTML = 'Output'	
           		
              },
         });
    }	
</script>
	
{% endblock %}